### PR TITLE
fix: avoid UB with unknown EtherType values and improve usability

### LINKED ISSUE #22: Undefined behavior when EtherType or IP protocol number don't match any enum descriminant
Hey,

if the EtherType or the IP protocol number don't match any of the defined discriminants in their respective enums, the behavior is undefined.

According to https://doc.rust-lang.org/reference/behavior-considered-undefined.html, producing an `a discriminant in an enum not included in the type definition` is undefined.

This could be fixed by replacing the enum with the corresponding integer and adding a `TryFrom` to the enum implementation.

### LINKED ISSUE #31: Implement TryFrom for crate enums
Implementing `TryFrom` on `EtherType` would allow users to write code like this:
```rust
let eth_type: u16 = 8;

match eth_type.try_into() {
    Ok(EtherType::Ipv4) => handle_ipv4(),
    Ok(EtherType::Ipv6) => handle_ipv6(),
    _ => return handle_others(),
}
```
instead of like this:
```rust
let eth_type: u16 = 8;

match eth_type {
    et if et == EtherType::Ipv4 as u16 => handle_ipv4(),
    et if et == EtherType::Ipv6 as u16 => handle_ipv6(),
    _ => return handle_others(),
}
```

This should be [trivial with `num_enum`](https://github.com/illicitonion/num_enum?tab=readme-ov-file#attempting-to-turn-a-primitive-into-an-enum-with-try_from) if adding it as a dependency is acceptable.

### PR DESCRIPTION
**Pull request by svencowart**
This PR refactors the handling of `EtherType` within `EthHdr` to prevent potential undefined behavior and enhance the ergonomics of the API.

**Problem:**

Previously, `EthHdr.ether_type` was of type `EtherType` (a `#[repr(u16)]` enum). If raw network data was cast to `EthHdr` and the underlying bytes for `ether_type` did not correspond to a defined discriminant in the `EtherType` enum, this would lead to undefined behavior in Rust. This is because Rust's memory safety guarantees for enums are violated if an invalid discriminant is present.

Additionally, this direct enum usage in `#[repr(C, packed)]` structs could complicate integration with zerocopy parsing, which prefers simpler, directly interpretable field types.

**Solution:**

1.  Modified `EthHdr`:
The `ether_type` field in `EthHdr` has been changed from `EtherType` to `u16`. This ensures that `EthHdr` always contains a valid integer value, regardless of whether it corresponds to a known protocol, thus avoiding undefined behavior. The `u16` value directly represents the big-endian EtherType as read from the network (after host CPU interpretation).
2.  `TryFrom<u16>` for `EtherType`
3.  `From<EtherType>` for `u16`
4.  Accessor and Constructor in `EthHdr`
    * `EthHdr::ether_type(&self) -> Result<EtherType, u16>`: A new method that attempts to convert the raw `u16` field into an `EtherType` enum using the `TryFrom` logic.
    * `EthHdr::new(dst_addr, src_addr, eth_type: EtherType) -> Self`: A constructor that takes an `EtherType` enum and correctly sets the `ether_type: u16` field using the `From` trait.
5.  Enhanced Documentation
6.  Basic Unit Tests

Fixes #22
Fixes #31

### CODE REVIEW

File: src/eth.rs [hunk 1]
```diff
@@ -10,14 +11,43 @@ pub struct EthHdr {
     /// Source MAC address.
     pub src_addr: [u8; 6],
     /// Protocol which is encapsulated in the payload of the frame.
-    pub ether_type: EtherType,
+    /// Indicates what type of data follows the Ethernet header (e.g., IPv4, IPv6, ARP)
+    pub ether_type: u16,
```
Comment (jecsand838) [inline src/eth.rs:15]: I'd imagine we'd want to keep this typed as `EtherType` if possible.

File: src/eth.rs [hunk 2]
```diff
@@ -38,3 +68,146 @@ pub enum EtherType {
...
+            v if v == Self::Infiniband as u16 => Ok(Self::Infiniband),
+            v if v == Self::LoopbackIeee8023 as u16 => Ok(Self::LoopbackIeee8023),
+            v if v == Self::Ieee8021QinQ1 as u16 => Ok(Self::Ieee8021QinQ1),
+            v if v == Self::Ieee8021QinQ2 as u16 => Ok(Self::Ieee8021QinQ2),
+            v if v == Self::Ieee8021QinQ3 as u16 => Ok(Self::Ieee8021QinQ3),
+            // For any other value, return an error
+            unknown_value => Err(unknown_value),
+        }
+    }
+}
```
Comment (jecsand838) [inline src/eth.rs:98]: Consider something like this to remove the repetitive guard conditions.

```suggestion
impl TryFrom<u16> for EtherType {
    type Error = u16; // Return the unknown value itself as the error

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match u16::from_be(value) {
            0x0060_u16 => Ok(EtherType::Loop),
            0x0800_u16 => Ok(EtherType::Ipv4),
            0x0806_u16 => Ok(EtherType::Arp),
            0x8100_u16 => Ok(EtherType::Ieee8021q),
            0x86DD_u16 => Ok(EtherType::Ipv6),
            0x88A8_u16 => Ok(EtherType::Ieee8021ad),
            0x88E5_u16 => Ok(EtherType::Ieee8021MacSec),
            0x88E7_u16 => Ok(EtherType::Ieee8021ah),
            0x88F5_u16 => Ok(EtherType::Ieee8021mvrp),
            0x8906_u16 => Ok(EtherType::FibreChannel),
            0x8915_u16 => Ok(EtherType::Infiniband),
            0x9000_u16 => Ok(EtherType::LoopbackIeee8023),
            0x9100_u16 => Ok(EtherType::Ieee8021QinQ1),
            0x9200_u16 => Ok(EtherType::Ieee8021QinQ2),
            0x9300_u16 => Ok(EtherType::Ieee8021QinQ3),
            _ => Err(value),
        }
    }
}
```

File: src/eth.rs (hunk 1 above)
Comment (svencowart) [reply src/eth.rs:15]: Note:
> Additionally, this direct enum usage in #[repr(C, packed)] structs could complicate integration with zerocopy parsing, which prefers simpler, directly interpretable field types.
And see: https://github.com/vadorovsky/network-types/issues/22#issuecomment-2353324782

If we want to allow zero-copy parsing, we need to change this to a directly interpretable field. I'm leaving it up to @vadorovsky to advise on the best direction.

**Review by vadorovsky — APPROVED** [review]
Thanks for the good catch! I will merge after sorting out the CI (I make a PR with a fix)

**Comment by vadorovsky** [comment]
@svencowart Your PR should become green after a rebase. :slightly_smiling_face:

**Comment by svencowart** [comment]
> @svencowart Your PR should become green after a rebase. 🙂

The tests are failing, but they seem unrelated to my changes. I can fix these in the next PR when I align all the other header type fields to directly interpretable field types.

**Comment by vadorovsky** [comment]
> The tests are failing, but they seem unrelated to my changes. I can fix these in the next PR when I align all the other header type fields to directly interpretable field types.

I'll try to fix these tests in #46

**Review by vadorovsky — APPROVED** [review]
